# Generated by Django 5.2.6 on 2025-09-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsbuilder', '0002_alter_formtemplate_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='conditional_logic',
            field=models.JSONField(blank=True, default=dict, help_text='JSON structure defining field visibility/validation conditions'),
        ),
    ]
